"""Resolves bundled asset paths in both dev mode (running from source) and
inside a PyInstaller-frozen exe (where files live under sys._MEIPASS
instead of next to this module).
"""
from __future__ import annotations

import sys
from pathlib import Path

_ASSETS_DIR_NAME = Path("smartdoc") / "presentation" / "assets"


def assets_dir() -> Path:
    frozen_base = getattr(sys, "_MEIPASS", None)
    if frozen_base:
        return Path(frozen_base) / _ASSETS_DIR_NAME
    return Path(__file__).parent / "assets"


def themes_dir() -> Path:
    """The theme packages (`themes/<id>/theme.json`, the schema and the validator). Next to `src/` when running from
    source, under sys._MEIPASS in the frozen exe (packaging/MewBook.spec bundles it)."""
    frozen_base = getattr(sys, "_MEIPASS", None)
    if frozen_base:
        return Path(frozen_base) / "themes"
    return Path(__file__).resolve().parents[3] / "themes"


def app_icon_path() -> Path:
    return assets_dir() / "app_icon.ico"


def brand_logo_path() -> Path:
    """The same brand mark as app_icon_path(), as a plain PNG -- used where
    a widget (e.g. the sidebar header) wants to embed it directly rather
    than set it as a window icon."""
    return assets_dir() / "brand_logo.png"


def legal_file_path(name: str) -> Path:
    """LICENSE / THIRD_PARTY_NOTICES.md. Frozen: at the root of the bundle (packaging/MewBook.spec
    datas '.'); from source: the repository root. May not exist (e.g. an installed wheel), so
    callers must cope with a missing file."""
    frozen_base = getattr(sys, "_MEIPASS", None)
    if frozen_base:
        return Path(frozen_base) / name
    return Path(__file__).resolve().parents[3] / name


def donate_qr_path() -> Path:
    """The author's VietQR donation code, shown by presentation/donate_dialog.py.
    May not exist (donate_dialog.py falls back to a text placeholder) --
    this is the author's own personal bank QR, not something generated by
    the app."""
    return assets_dir() / "donate_qr.png"
